---
title: "PCA filter"
author: "Stefanie Bienert"
date: "8/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# How can this work
Take the summarized experiment and calculate the Variance across each gene using the `rowVars` function. Then subset the data to only use the top 500 genes with max variance.

```{r}
object <- HermesData(summarized_experiment)
object2 <- hermes::top_genes(
  object,
  assay_name = "counts",
  summary_fun = rowVars,
  n_top = 500,
)
object3 <- object[rowData(object)$GeneID %in% as.character(object2$name)]

```

# PCA function
```{r}
calc_pca_filtered <- function(object,
                     assay_name = "counts",
                     varfilter) {
  assert_that(
    is_hermes_data(object),
    is.string(assay_name)
  )
  
  x_samples <- assay(object, assay_name)
  
  x_samples_filter <- top_genes(
    object = object,
    assay_name = assay_name,
    summary_fun = rowVars,
    n_top = varfilter,
  )
  x_samples_filtered <- x_samples[rownames(x_samples) %in% as.character(x_samples_filter$name)]
  x_genes <- t(x_samples_filtered)
  gene_is_constant <- apply(x_genes, MARGIN = 2L, FUN = S4Vectors::isConstant)
  x_genes_remaining <- x_genes[, !gene_is_constant]
  
  pca <- stats::prcomp(
    x = x_genes_remaining, #x_samples_filtered
    center = TRUE,
    scale = TRUE,
    tol = sqrt(.Machine$double.eps)
  )
  
  .HermesDataPca(pca)
}
```

# Test it out
```{r}
object <- HermesData(summarized_experiment)
result <- calc_pca_filtered(object, assay_name = "counts", 500)
summary(result)
```

```{r}
autoplot(result)
```


